import{MESSAGE_TYPES as P,REQUEST_MODES as O,generateRequestId as k}from"./constants.js";import{StreamHandler as v,NormalRequestHandler as B}from"./handlers.js";import{RequestManager as $}from"./requestManager.js";import{scrapeSuiteScriptModules as q}from"../../modules/suiteScriptScraper.js";const I=new $,H="SCRAPE_SUITESCRIPT_MODULES",F=200,R=new Set(["script","style","noscript","svg"]),X=new Set(["article","aside","blockquote","div","dl","fieldset","figure","footer","form","header","main","nav","ol","p","section","table","ul"]),x=new Set(["h1","h2","h3","h4","h5","h6"]),T=E=>E.replace(/\r/g,"").replace(/[ \t\f\v]+/g," ").replace(/ *\n */g,`
`).replace(/\n{3,}/g,`

`).trim(),U=(E,d)=>{const l=String(E??"").trim();if(!l)return"";const n=l.toLowerCase();if(n.startsWith("javascript:")||n.startsWith("mailto:")||n.startsWith("tel:"))return"";try{const h=new URL(l,d).href;return h.startsWith("http://")||h.startsWith("https://")?h:""}catch{return""}},G=E=>{let d=E;for(;d;){let l=d.previousElementSibling;for(;l;){if(x.has(l.tagName.toLowerCase()))return T(l.textContent??"");const n=Array.from(l.querySelectorAll("h1,h2,h3,h4,h5,h6")),h=n[n.length-1];if(h)return T(h.textContent??"");l=l.previousElementSibling}d=d.parentElement}return""},z=(E,d)=>{const l=[],n=new Set,h=(u,c,g)=>{if(!g)return;const s=T(c)||g,o=`${s}
${g}`;if(!n.has(o)&&(n.add(o),l.length<F)){const r=G(u);l.push({text:s,url:g,...r?{section:r}:{}})}},f=u=>Array.from(u.childNodes).map(D).join(""),D=u=>{if(u.nodeType===Node.TEXT_NODE)return(u.textContent??"").replace(/\s+/g," ");if(u.nodeType!==Node.ELEMENT_NODE)return"";const c=u,g=c.tagName.toLowerCase();if(R.has(g))return"";if(g==="br")return`
`;if(g==="a"){const o=T(f(c)||c.textContent||""),r=U(c.getAttribute("href"),d);return r?(h(c,o,r),o||r):o}if(g==="pre")return`

${(c.textContent??"").trim()}

`;if(g==="code")return T(c.textContent??"");if(g==="li")return`
${T(f(c))}`;if(g==="tr"){const o=Array.from(c.children).filter(r=>["td","th"].includes(r.tagName.toLowerCase())).map(r=>T(f(r))).filter(Boolean);return o.length?`
${o.join(" ")}`:""}if(x.has(g))return`

${T(f(c))}

`;const s=f(c);return X.has(g)?`

${s}

`:s};return{content:T(D(E)),links:l,linkCount:n.size,linksTruncated:n.size>l.length}},Q=E=>{chrome.runtime.onConnect.addListener(d=>{d.name==="stream-api"&&(d.onMessage.addListener(l=>{const{action:n,data:h,mode:f,tabId:D}=l,w=k();if(f!==O.STREAM)return;if(n===H){q(h?.baseUrl,c=>{d.postMessage({...c,requestId:w})});return}const u=new v(w,E,c=>{d.postMessage(c)});I.addRequest(w,u),u.start(),window.postMessage({type:P.FROM_EXTENSION,capability:E,payload:{action:n,data:h,requestId:w,mode:f}},window.location.origin)}),d.onDisconnect.addListener(()=>{I.abortAll()}))}),chrome.runtime.onMessage.addListener((d,l,n)=>{const{action:h,data:f,mode:D=O.NORMAL}=d,w=k();if(D!==O.NORMAL)return;if(h==="FETCH_HELP_PAGE"){const s=f?.url??"",o=f?.operation??"read",r=f?.baseUrl??"";return fetch(s,{credentials:"include"}).then(e=>{if(!e.ok)throw new Error(`HTTP ${e.status}`);return e.text()}).then(e=>{const t=new DOMParser().parseFromString(e,"text/html");if(o==="search"){const i=t.querySelectorAll(".result-title"),m=t.querySelectorAll(".result-body"),p=[];i.forEach((b,L)=>{const C=b.querySelector("a"),S=(C?.textContent??b.textContent??"").trim(),N=C?.getAttribute("href")??"",y=U(N,s||r),_=(m[L]?.textContent??"").trim();S&&y&&p.push({title:S,url:y,summary:_})}),n({status:"ok",message:{results:p}})}else{const i=t.getElementById("nshelp_page")??t.querySelector(".nshelp_page")??t.querySelector("main")??t.body,m=T(i?.querySelector("h1")?.textContent??t.querySelector("title")?.textContent??""),p=z(i,s);n({status:"ok",message:{title:m,...p}})}}).catch(e=>n({status:"error",message:String(e?.message??e)})),!0}const u=s=>{const o=[];let r="",e=!1;for(let a=0;a<s.length;a++){const t=s[a];t==='"'?e&&s[a+1]==='"'?(r+='"',a++):e=!e:t===","&&!e?(o.push(r.trim()),r=""):r+=t}return o.push(r.trim()),o};if(h==="FETCH_BUNDLES"){const{domain:s,bundleType:o="both"}=f??{},r={Name:"name","Bundle ID":"bundleId",Version:"version","App ID":"appId",Abstract:"abstract","Created By":"createdBy","Created On":"createdOn","Last Update":"lastUpdate"},e=t=>{const i=`https://${s}/app/bundler/bundlelist.csv?type=${t}&sortcol=bundlename&sortdir=ASC&csv=Export`,m=t==="I"?"installed":"created";return fetch(i,{credentials:"include"}).then(p=>{if(!p.ok)throw new Error(`HTTP ${p.status}`);return p.text()}).then(p=>{const b=p.split(`
`).filter(S=>S.trim()!=="");if(b.length<2)return[];b.shift();const L=u(b[0]),C=[];for(let S=1;S<b.length;S++){const N=u(b[S]),y={type:m};L.forEach((_,A)=>{r[_]&&(y[r[_]]=N[A]??"")}),y.bundleId&&C.push(y)}return C})},a=o==="I"?["I"]:o==="S"?["S"]:["I","S"];return Promise.all(a.map(e)).then(t=>{const i=t.flat();n({status:"ok",message:{bundles:i}})}).catch(t=>n({status:"error",message:String(t?.message??t)})),!0}if(h==="FETCH_BUNDLE_COMPONENTS"){const{domain:s,bundleId:o}=f??{},e=((s??"").split(".")[0]??"").toLowerCase().replace(/-/g,"_"),a=`https://${s}/app/bundler/bundlecontents.csv?csv=Export&OfficeXML=F&id=${o}&fetchcompid=${e}`,t=i=>{if(!i)return!1;const m=u(i);return!!m[0]&&!m[1]&&!m[2]&&!m[3]};return fetch(a,{credentials:"include"}).then(i=>{if(!i.ok)throw new Error(`HTTP ${i.status}`);return i.text()}).then(i=>{const m=i.split(`
`).filter(C=>C.trim()!=="");if(m.length<2){n({status:"ok",message:{components:[]}});return}let p="",b="";const L=[];for(let C=1;C<m.length;C++){const S=m[C],N=m[C+1]??"";if(t(S)){N&&!t(N)?b=u(S)[0]??"":(p=u(S)[0]??"",b="");continue}const[y,_,A,M]=u(S);y&&L.push({name:y,id:_??"",referencedBy:A??"",isLocked:!!M,category:p,subCategory:b})}n({status:"ok",message:{components:L}})}).catch(i=>n({status:"error",message:String(i?.message??i)})),!0}const c=(s,o)=>{const e=((s??"").split(".")[0]??"").replace(/-/g,"_").toUpperCase(),a=new URL(`https://${s}/app/bundler/bundledetails.nl`);return a.searchParams.set("selectedtab","tab"),a.searchParams.set("id",String(o)),a.searchParams.set("sourcecompanyid",e),a.searchParams.set("domain",String(s).toLowerCase().includes("-sb")?"SANDBOX":"PRODUCTION"),a.searchParams.set("loadsuiteappdata","T"),a.searchParams.set("whence",""),a.toString()};if(h==="CHECK_BUNDLE_SDF_CONVERSION"){const{domain:s,bundleId:o}=f??{},r=c(s,o);return fetch(r,{credentials:"include"}).then(e=>{if(!e.ok)throw new Error(`HTTP ${e.status} checking SDF conversion status`);return e.text()}).then(e=>{const a=(e.match(/<button\b[^>]*>/gi)??[]).find(m=>/\bid\s*=\s*(["'])converttoacp\1/i.test(m)),t=!!a,i=a?/\sdisabled(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+))?(?=\s|>)/i.test(a):!1;n({status:"ok",message:{buttonFound:t,disabled:i,canConvert:t&&!i,inProgress:t&&i,detailsUrl:r}})}).catch(e=>n({status:"error",message:String(e?.message??e)})),!0}if(h==="START_BUNDLE_SDF_CONVERSION"){const{domain:s,bundleId:o,detailsUrl:r}=f??{},e=r||c(s,o),a=new URL(`https://${s}/app/suiteapp/bundlesuiteappconvert/convert.nl`);return a.searchParams.set("bundleid",String(o)),fetch(a,{method:"GET",credentials:"include",referrer:e,referrerPolicy:"strict-origin-when-cross-origin"}).then(t=>{if(!t.ok)throw new Error(`HTTP ${t.status} starting SDF conversion`);n({status:"ok",message:{started:!0}})}).catch(t=>n({status:"error",message:String(t?.message??t)})),!0}const g=new B(w,E,n);return I.addRequest(w,g),g.start(),window.postMessage({type:P.FROM_EXTENSION,capability:E,payload:{...d,requestId:w}},window.location.origin),!0}),window.addEventListener("beforeunload",()=>{console.log("Content script unloading, aborting all requests..."),I.abortAll()})};export{Q as setupMessageListener};
